### ISSUE TITLE
Dependency on dearpygui 1.6.2?

### ISSUE THREAD

**Issue by now-its-dark** [EMATech/MidiExplorer#3]
Hi there,
This seems like a great tool! I've been trying to install midiexplorer on macOS, but pip complains that that there is a dependency on the 1.6.2 version of dearpygui specifically, and it can't acquire that version.
Is it actually dependent on that exact version, or would 1.6.2 or later be compatible? I believe the current version is now 1.9.1.
Thanks!

**Comment by rdoursenaud** [comment]
Hi!

Thanks for the kind words.

You're probably trying v0.0.1a2 from PyPi which is quite outdated.
Please try the current `main` branch which depends on v1.8.0 of `dearpygui` and should work.
I haven't validated v1.9.x yet.
The new build system uses [hatch](https://hatch.pypa.io/latest/) and should be straightforward by following their docs.
I haven't published another alpha to PyPi because I'm honing a bunch of new features first ;)
Sorry for the inconvenience and let me know if you need any help.

Oh and I'd love to hear how it's going with MacOS.
My initial testing on this OS has been very superficial.

The project is a work in progress, so expect some rough edges.

Thank you.

**Comment by rdoursenaud** [comment]
Oh and for why the version was pinned specifically to v1.6.2, see https://github.com/EMATech/midiexplorer/commit/37ac890867cbc18333c0f79104e8a4346734f3d1.

**Comment by AL1-1956** [comment]
Hello 
I have the same issue
Successfully installed dearpygui 1.8.0

But when I try to install with "pipx install midiexplorer'

I get 

$ pipx install midiexplorer
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\ALAIN\.local\pipx\logs\cmd_2023-09-12_08.47.41_pip_errors.log

pip seemed to fail to build package:    midiexplorer

Some possibly relevant errors from pip install:
    ERROR: Cannot install midiexplorer==0.0.1a0, midiexplorer==0.0.1a1 and midiexplorer==0.0.1a2 because these package versions have conflicting dependencies.

===========================================================
And when i read the logs it says

PIP STDOUT
----------
Collecting midiexplorer
  Using cached midiexplorer-0.0.1a2-py3-none-any.whl (362 kB)
Collecting dearpygui-ext==0.9.5 (from midiexplorer)
  Using cached dearpygui_ext-0.9.5-py3-none-any.whl (9.3 kB)
INFO: pip is looking at multiple versions of midiexplorer to determine which version is compatible with other requirements. This could take a while.
Collecting midiexplorer
  Using cached midiexplorer-0.0.1a1-py3-none-any.whl (358 kB)
  Using cached midiexplorer-0.0.1a0-py3-none-any.whl (350 kB)

The conflict is caused by:
    midiexplorer 0.0.1a2 depends on dearpygui==1.6.2
    midiexplorer 0.0.1a1 depends on dearpygui==1.6.2
    midiexplorer 0.0.1a0 depends on dearpygui==1.6.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict


PIP STDERR
----------
ERROR: Cannot install midiexplorer==0.0.1a0, midiexplorer==0.0.1a1 and midiexplorer==0.0.1a2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
==============================================================
I understand that you said there is a newer version of midiExplorer , but I do not know how to get it

(Apologize for my poor English but I am French)

By the way Great Thanks for MIDO

Alain

**Comment by rdoursenaud** [comment]
Hi and thank you for the detailed report.
I've just published an alpha 3 that should allow you to install.
Sorry for taking this long.
Please report back, thanks!

Keep in mind it's still an early alpha with unfinished & not stabilized features.
Looking forward to your feedback.

**Comment by AL1-1956** [comment]
Sorry to bother you with stupid questions

I am now 67 yo , so I know MIDI for a long time .

But despite of that I am a fresh (and French) user of Python and I do not know what to do 
with the MidiExplorer-main.zip file that I downloaded

and I do not have the skills to make a  compiled version 

Anyway 
Thank you for your answser and have a great (sunny ??) day

**Comment by rdoursenaud** [comment]
@AL1-1956 Don't worry, I'm here to help ;)

You seem to be using Microsoft Windows.
I've just added an experimental compiled build to the [new release](https://github.com/EMATech/MidiExplorer/releases/tag/0.0.1a5) that should work for you.

The alternative is to install using `pipx`, just as you did before.
It should now pick-up the new version and install it without issue.

Please let me know if you encounter any issue.

**Comment by AL1-1956** [comment]
Ok I installed MidiExplorer.exe successfully 

ALAIN@KIT MINGW64 /
$ pipx install midiexplorer
  installed package midiexplorer 0.0.1a5, installed using Python 3.11.4
  These apps are now globally available
    - midiexplorer.exe
done! ✨ 🌟 ✨
=======================================================================
Now for some testing

Thank You

**Comment by rdoursenaud** [comment]
Thanks for sharing the good news! 🎉

**Comment by AL1-1956** [comment]
Sorry for the BIIIIIGGGGG text , i do not know why this happens

**Comment by AL1-1956** [comment]
Thank you for the info I removed the big text , I do not want to seem like a yelling person

**Comment by AL1-1956** [comment]
So I now have connected my KorgNanoKontrol 2 on input and I can see the CC Events flowing .
There is some kind of latency when I draw  the sliders very quickly but I guess this is normal.
With other controls who only send 0 or 127 this is perfect

On this computer I do not have a midi out device , except "Coolsoft Midi Mapper" and "Microsoft GS" 
so for now I cannot test the midi out options

I have a question , since I do not see where the .exe file is , I cannot have an Icon for launtching it.

And I have to open a cmd and type midiexplorer each time   

Thank you a lot for your confidence in myself for beta-testting

Alain

**Comment by AL1-1956** [comment]
Okay , I found out where the exe file was 

c:\Users\ALAIN\.local\bin\midiexplorer.exe
and made a link icon on my desktop.

Much more confortable this way...
Tested the MidiFile dump function (very informative)

more "test" results to come soon

Have a nice evening 

Alain

**Comment by rdoursenaud** [comment]
9a6518ff2d2e818fa22e27ad3d92ca780f4376d6 introduces DearPyGui 2.0 support.
